app = "system32-frosty-cloud-4611"

primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[env]

[[mounts]]
  source = "users_data"
  destination = "/data"

[processes]
  bot = "python main.py"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["bot"]

  [[services.ports]]
    port = 8080
