app = "pptxbot"
primary_region = "fra"

[build]
  dockerfile = "Dockerfile"

[processes]
  bot = "python3 main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[checks]
  skip = true
[mounts]
  source="users_data"
  destination="/data"
